// https://github.com/AlmostReliable/morejs/wiki/Villager-Trades
MoreJSEvents.villagerTrades((event) => {
    const farmerTrades1 = ['pamhc2crops:raspberryitem', 'pamhc2crops:rhubarbitem', 'pamhc2crops:rutabagaitem', 'pamhc2crops:scallionitem', 'pamhc2crops:sesameseedsitem', 'pamhc2crops:spiceleafitem', 'pamhc2crops:strawberryitem', 'pamhc2crops:sweetpotatoitem', 'pamhc2crops:taroitem', 'pamhc2crops:agaveitem', 'pamhc2crops:arrowrootitem', 'pamhc2crops:blackberryitem', 'pamhc2crops:blueberryitem', 'pamhc2crops:cactusfruititem', 'pamhc2crops:candleberryitem', 'pamhc2crops:cantaloupeitem', 'pamhc2crops:cassavaitem', 'pamhc2crops:coffeebeanitem', 'pamhc2crops:cranberryitem', 'pamhc2crops:elderberryitem', 'pamhc2crops:garlicitem', 'pamhc2crops:gingeritem', 'pamhc2crops:grapeitem', 'pamhc2crops:greengrapeitem', 'pamhc2crops:huckleberryitem', 'pamhc2crops:jicamaitem', 'pamhc2crops:juniperberryitem', 'pamhc2crops:kiwiitem', 'pamhc2crops:kohlrabiitem', 'pamhc2crops:leekitem', 'pamhc2crops:mulberryitem', 'pamhc2crops:mustardseedsitem', 'pamhc2crops:parsnipitem', 'pamhc2crops:peanutitem', 'pamhc2crops:pineappleitem', 'pamhc2crops:radishitem', 'pamhc2crops:tealeafitem', 'pamhc2crops:turnipitem', 'pamhc2crops:waterchestnutitem', 'pamhc2crops:whitemushroomitem', 'pamhc2crops:alfalfaitem', 'pamhc2crops:aloeitem', 'pamhc2crops:barrelcactusitem', 'pamhc2crops:canolaitem', 'pamhc2crops:cattailitem', 'pamhc2crops:cloudberryitem', 'pamhc2crops:lotusitem', 'pamhc2crops:nettlesitem', 'pamhc2crops:truffleitem', 'pamhc2crops:wolfberryitem', 'pamhc2crops:guaranaitem', 'pamhc2crops:papyrusitem', 'pamhc2crops:sunchokeitem']
    farmerTrades1.forEach(trade => {
        event.addTrade("farmer", 1, `26x ${trade}`, 'minecraft:emerald');
    })
    const farmerTrades2 = ['pamhc2crops:artichokeitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:bellpepperitem', 'pamhc2crops:broccoliitem', 'pamhc2crops:brusselsproutitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:celeryitem', 'pamhc2crops:chilipepperitem', 'pamhc2crops:cucumberitem', 'pamhc2crops:eggplantitem', 'pamhc2crops:kaleitem', 'pamhc2crops:lettuceitem', 'pamhc2crops:okraitem', 'pamhc2crops:peasitem', 'pamhc2crops:spinachitem', 'pamhc2crops:tomatilloitem', 'pamhc2crops:wintersquashitem', 'pamhc2crops:zucchiniitem', 'pamhc2crops:chiaitem', 'pamhc2crops:nopalesitem', 'pamhc2crops:bokchoyitem', 'pamhc2crops:calabashitem']
    farmerTrades2.forEach(trade => {
        event.addTrade("farmer", 1, `22x ${trade}`, 'minecraft:emerald');
    })
    const farmerTrades3 = ['pamhc2crops:amaranthitem', 'pamhc2crops:barleyitem', 'pamhc2crops:beanitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:cornitem', 'pamhc2crops:cottonitem', 'pamhc2crops:juteitem', 'pamhc2crops:kenafitem', 'pamhc2crops:lentilitem', 'pamhc2crops:milletitem', 'pamhc2crops:oatsitem', 'pamhc2crops:quinoaitem', 'pamhc2crops:ryeitem', 'pamhc2crops:sisalitem', 'pamhc2crops:soybeanitem', 'pamhc2crops:sorghumitem', 'pamhc2crops:yuccaitem']
    farmerTrades3.forEach(trade => {
        event.addTrade("farmer", 1, `20x ${trade}`, 'minecraft:emerald');
    })
});