LootJS.modifiers(event => {
    event.addBlockLootModifier("minecraft:dirt")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:wooden_trowel')
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:grass_block")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:wooden_trowel')
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:dirt_path")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:wooden_trowel')
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .removeLoot("minecraft:dirt");

    event.addBlockLootModifier("minecraft:dirt")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot("infinite_horizons_tweaks:stone_pebble").randomChance(0.5)
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.5)
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:grass_block")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot("infinite_horizons_tweaks:stone_pebble").randomChance(0.5)
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.5)
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:dirt_block")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot("kubejs:stone_pebble").randomChance(0.5)
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.5)
        .removeLoot("minecraft:dirt");

    event.addBlockLootModifier("minecraft:dirt")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .randomChance(0.5)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:deepslate_pebble")
        .addLoot("kubejs:limestone_pebble")
        .randomChance(0.75)
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:grass_block")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .randomChance(0.5)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:deepslate_pebble")
        .addLoot("kubejs:limestone_pebble")
        .randomChance(0.75)
        .removeLoot("minecraft:dirt");
    event.addBlockLootModifier("minecraft:dirt_path")
        .removeLoot('twigs:pebble')
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot("infinite_horizons_tweaks:stone_pebble")
        .randomChance(0.5)
        .addLoot("infinite_horizons_tweaks:andesite_pebble")
        .addLoot("infinite_horizons_tweaks:granite_pebble")
        .addLoot("infinite_horizons_tweaks:diorite_pebble")
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:deepslate_pebble")
        .addLoot("kubejs:limestone_pebble")
        .randomChance(0.75)
        .removeLoot("minecraft:dirt");

    event.addBlockLootModifier("minecraft:gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.25)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("minecraft:gravel");
    event.addBlockLootModifier("kubejs:andesite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.25)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:andesite_gravel");
    event.addBlockLootModifier("kubejs:granite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.25)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:granite_gravel");
    event.addBlockLootModifier("kubejs:diorite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:stone_trowel')
        .randomChance(0.5)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.25)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:diorite_gravel");

    event.addBlockLootModifier("minecraft:blocks/gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.5)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("minecraft:gravel");
    event.addBlockLootModifier("kubejs:andesite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.5)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:andesite_gravel");
    event.addBlockLootModifier("kubejs:granite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.5)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:granite_gravel");
    event.addBlockLootModifier("kubejs:diorite_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:stone_pebble')
        .randomChance(0.5)
        .addLoot('minecraft:iron_nugget')
        .removeLoot("kubejs:diorite_gravel");

    event.addBlockLootModifier("kubejs:tuff_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:tuff_pebble')
        .randomChance(0.25)
        .addLoot("infinite_horizons_tweaks:deepslate_pebble")
        .randomChance(0.75)
        .removeLoot("kubejs:tuff_gravel");

    event.addBlockLootModifier("kubejs:deepslate_gravel")
        .matchEquip('mainhand', 'infinite_horizons_tweaks:iron_trowel')
        .randomChance(0.75)
        .addLoot('infinite_horizons_tweaks:deepslate_pebble')
        .randomChance(0.25)
        .addLoot('infinite_horizons_tweaks:tuff_pebble')
        .randomChance(0.75)
        .removeLoot("kubejs:deepslate_gravel");
});